name: build opt package
on: [push]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: install mpy-cross
      run: pip install mpy-cross
    - name: run compilation
      run: bash ./compile.sh
    - uses: actions/upload-artifact@v3
      with:
        name: opt-package
        path: output/*